### ISSUE TITLE
help

### ISSUE THREAD

**Issue by aison45** [owncloud/craft-blueprints-owncloud#14]
ssh: connect to host gitea.owncloud.services port 2222: Connection timed out
fatal: Could not read from remote repository.

**Comment by DeepDiver1975** [comment]
> ssh: connect to host gitea.owncloud.services port 2222: Connection timed out

only reachable via vpn to employees of owncloud GmbH

**Comment by michaelstingl** [comment]
@TheOneRing @dschmidt make the connection to internal systems optional?

**Comment by TheOneRing** [comment]
It is optional and off by default. Maybe we should document it.

**Comment by gsoareslima** [comment]
How can I access gitea.owncloud.services:2222 to use **craft ---fetch client-plugin-vfs-win**?
