### ISSUE TITLE
error while 'craft owncloud-client'

### ISSUE THREAD

**Issue by vaibhavtekam** [owncloud/craft-blueprints-owncloud#36]
I am getting this error. 
Tried on different systems as well. 

Patching C:\_\83de3e81\image-RelWithDebInfo-2.2.10\lib\pkgconfig\expat.pc: replacing b'C:/builds/sysadmin/ci-management/windows-msvc2019_64-cl' with b'C:/CraftRoot'
*** Craft all succeeded: libs/expat after 3 seconds ***
========================================================================================================================*** Handling package: dev-utils/msys, action: all ***
*** Action: fetch-binary for dev-utils/msys ***
Could not find dev-utils/msys=base in https://files.kde.org/craft/master/23.09/windows/cl/msvc2019/x86_64/RelWithDebInfoCould not find dev-utils/msys=base in https://files.kde.org/craft/master/23.09/windows/cl/msvc2019/x86_64/Release
*** dev-utils/msys not found in cache ***
*** Action: fetch for dev-utils/msys ***
wget https://github.com/msys2/msys2-installer/releases/download/2023-01-27/msys2-base-x86_64-20230127.tar.xz
C:/CraftRoot/download/archive 100%[=================================================>]  56.38M  11.3MB/s    in 5.0s
*** Craft all succeeded: dev-utils/msys after 6 seconds ***
C:\CraftRoot\craft\blueprints\dev-utils\_windows\msys\msys.py failed:
type object 'HashAlgorithm' has no attribute '__getattr__'
Craft stopped with out completing ['dev-utils/msys', 'libs/libffi', 'libs/iconv', 'libs/liblzma', 'dev-utils/pkg-config', 'libs/icu', 'libs/libxml2', 'libs/gettext', 'python-modules/meson', 'libs/glib', 'libs/dbus', 'libs/libzstd', 'libs/libpng', 'libs/libjpeg-turbo', 'libs/sqlite', 'libs/libbzip2', 'libs/pcre2', 'libs/brotli', 'libs/freetype', 'libs/harfbuzz', 'dev-utils/qtbinpatcher', 'dev-utils/flexbison', 'libs/qt5/qtbase', 'libs/qt/qtbase', 'craft/craft-blueprints-owncloud', 'libs/libre-graph-api-cpp-qt-client', 'libs/qt5/qtsvg', 'libs/d3dcompiler', 'libs/qt5/qtdeclarative', 'libs/qt5/qttools', 'libs/qt5/qttranslations', 'libs/qt/qttranslations', 'libs/qt/qtsvg', 'libs/tiff', 'libs/giflib', 'libs/webp', 'libs/qt5/qtimageformats', 'libs/qt/qtimageformats', 'libs/qt5/qtxmlpatterns', 'libs/qt5/qtwinextras', 'libs/qt/qttools', 'qt-libs/qtkeychain', 'libs/kdsingleapplication', 'dev-utils/icoutils', 'kde/frameworks/extra-cmake-modules', 'libs/nlohmann-json', 'owncloud/owncloud-client']
PS C:\CraftRoot>

**Comment by vansante** [comment]
I had the same problem, I resolved it by downgrading python to 3.11.x.

**Comment by TheOneRing** [comment]
Could you run craft with -vvv and paste the stack trace?
BTW: If you want to have the same sdk we use on the ci you could give https://github.com/owncloud/ownbuild a try. It will setup craft environment for a branch of ownCloud. Just call the craftenv.ps1 from the installed craft root.

**Comment by vaibhavtekam** [comment]
Downgrading Python from 3.12 to 3.11 did resolved that issue. 

But then stared getting error for QT6, which is already installed. Shouldn't it be taking the path on its own. 

Craft               : C:\CraftRoot
Version             : master
ABI                 : windows-cl-msvc2019-x86_64
Download directory  : C:\CraftRoot\download
========================================================================================================================
*** Handling package: owncloud/owncloud-client, action: all ***
*** Action: fetch-binary for owncloud/owncloud-client ***
Could not find owncloud/owncloud-client=master in https://files.kde.org/craft/master/23.09/windows/cl/msvc2019/x86_64/RelWithDebInfo
Could not find owncloud/owncloud-client=master in https://files.kde.org/craft/master/23.09/windows/cl/msvc2019/x86_64/Release
*** owncloud/owncloud-client not found in cache ***
*** Action: fetch for owncloud/owncloud-client ***
executing command: C:\Program Files\Git\cmd\git.exe -c color.ui=always fetch
executing command: C:\Program Files\Git\cmd\git.exe -c color.ui=always checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
executing command: C:\Program Files\Git\cmd\git.exe -c color.ui=always checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
executing command: C:\Program Files\Git\cmd\git.exe -c color.ui=always submodule update --init --recursive
*** Action: unpack for owncloud/owncloud-client ***
*** Action: configure for owncloud/owncloud-client ***
executing command: C:\CraftRoot\dev-utils\bin\cmake.exe -G Ninja -DBUILD_TESTING=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=C:/CraftRoot -DCMAKE_PREFIX_PATH=C:/CraftRoot -DCMAKE_REQUIRED_INCLUDES=C:/CraftRoot/include -DCMAKE_C_STANDARD_INCLUDE_DIRECTORIES=C:/CraftRoot/include -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=ON -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -S C:\_\30b36579\owncloud-client
-- The CXX compiler identification is MSVC 19.29.30152.0
-- The C compiler identification is MSVC 19.29.30152.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
--

CMake Error at CMakeLists.txt:21 (find_package):
  Could not find a package configuration file provided by "QT" (requested
  version 6.2) with any of the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "QT" to CMAKE_PREFIX_PATH or set "QT_DIR" to
  a directory containing one of the above files.  If "QT" provides a separate
  development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "C:/_/41bb79b4/build/CMakeFiles/CMakeOutput.log".
Command ['C:\\CraftRoot\\dev-utils\\bin\\cmake.exe', '-G', 'Ninja', '-DBUILD_TESTING=ON', '-DBUILD_SHARED_LIBS=ON', '-DCMAKE_INSTALL_PREFIX=C:/CraftRoot', '-DCMAKE_PREFIX_PATH=C:/CraftRoot', '-DCMAKE_REQUIRED_INCLUDES=C:/CraftRoot/include', '-DCMAKE_C_STANDARD_INCLUDE_DIRECTORIES=C:/CraftRoot/include', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=ON', '-DKDE_INSTALL_USE_QT_SYS_PATHS=ON', '-S', 'C:\\_\\30b36579\\owncloud-client'] failed with exit code 1
Action: configure for owncloud/owncloud-client:master FAILED
*** Craft all succeeded: owncloud/owncloud-client after 4 seconds ***
fatal error: package owncloud/owncloud-client all failed
Craft stopped with out completing ['owncloud/owncloud-client']
PS C:\CraftRoot>

**Comment by TheOneRing** [comment]
Please use ownbuild, which will take care of the proper configuration or join https://matrix.to/#/#kde-craft:kde.org for craft support.

**Comment by vaibhavtekam** [comment]
thanks @TheOneRing 

I follwed your instructions, but still get same error. And this was done from fresh Craft installation. 

-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
--

CMake Error at CMakeLists.txt:21 (find_package):
  Could not find a package configuration file provided by "QT" (requested
  version 6.2) with any of the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "QT" to CMAKE_PREFIX_PATH or set "QT_DIR" to
  a directory containing one of the above files.  If "QT" provides a separate
  development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "C:/_/da198b0e/build/CMakeFiles/CMakeOutput.log".
Command ['C:\\Craft\\dev-utils\\bin\\cmake.exe', '-G', 'Ninja', '-DBUILD_TESTING=ON', '-DBUILD_SHARED_LIBS=ON', '-DCMAKE_INSTALL_PREFIX=C:/Craft', '-DCMAKE_PREFIX_PATH=C:/Craft', '-DCMAKE_REQUIRED_INCLUDES=C:/Craft/include', '-DCMAKE_C_STANDARD_INCLUDE_DIRECTORIES=C:/Craft/include', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=ON', '-DKDE_INSTALL_USE_QT_SYS_PATHS=ON', '-S', 'C:\\_\\29e8dea\\owncloud-client'] failed with exit code 1
Action: configure for owncloud/owncloud-client:master FAILED
*** Craft all succeeded: owncloud/owncloud-client after 4 seconds ***
fatal error: package owncloud/owncloud-client all failed
Craft stopped with out completing ['owncloud/owncloud-client']
Command C:\Craft\etc\virtualenv\3\Scripts\python.exe -X utf8 -u C:\Craft\ownbuild\master\windows-cl-msvc2022-x86_64-debug\craft\bin\craft.py owncloud-client failed with exit code: 1
PS C:\Craft\ownbuild> python3 ownbuild.py --branch master --target windows-cl-msvc2022-x86_64-debug owncloud-client
